"""Initial Migration

Revision ID: 4f9b12a5daae
Revises: 
Create Date: 2024-06-12 10:45:51.675417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f9b12a5daae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloomdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('influencer_data',
    sa.Column('bloom_data_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('niche', sa.String(length=30), nullable=False),
    sa.Column('reach', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['bloom_data_id'], ['bloomdata.id'], ),
    sa.PrimaryKeyConstraint('bloom_data_id'),
    sa.UniqueConstraint('bloom_data_id')
    )
    op.create_table('sponsor_data',
    sa.Column('bloom_data_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=30), nullable=False),
    sa.Column('industry', sa.String(length=30), nullable=False),
    sa.Column('budget', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['bloom_data_id'], ['bloomdata.id'], ),
    sa.PrimaryKeyConstraint('bloom_data_id'),
    sa.UniqueConstraint('bloom_data_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sponsor_data')
    op.drop_table('influencer_data')
    op.drop_table('bloomdata')
    # ### end Alembic commands ###
