"""Add unique constraint to campaign_requests

Revision ID: e226311e9095
Revises: 
Create Date: 2024-08-11 14:22:08.855913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e226311e9095'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloomdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('niche', sa.String(length=50), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('influencer_data',
    sa.Column('bloom_data_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('niche', sa.String(length=30), nullable=False),
    sa.Column('reach', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['bloom_data_id'], ['bloomdata.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bloom_data_id'),
    sa.UniqueConstraint('bloom_data_id')
    )
    op.create_table('sponsor_data',
    sa.Column('bloom_data_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=30), nullable=False),
    sa.Column('industry', sa.String(length=30), nullable=False),
    sa.Column('budget', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['bloom_data_id'], ['bloomdata.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bloom_data_id'),
    sa.UniqueConstraint('bloom_data_id')
    )
    op.create_table('campaign_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.Integer(), nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencer_data.bloom_data_id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsor_data.bloom_data_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'influencer_id', name='unique_campaign_influencer')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_requests')
    op.drop_table('sponsor_data')
    op.drop_table('influencer_data')
    op.drop_table('campaigns')
    op.drop_table('bloomdata')
    # ### end Alembic commands ###
